name: Build and Publish

on:
  workflow_dispatch:

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Reqs.txt
    - name: Build Linux executable
      run: pyinstaller -F -i PyC.ico --add-data "Inter.ttf;." --add-data "icomoon.ttf;." --add-data "PyC.ico;." PyC.py --noconsole
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-executable
        path: dist/PyC
